apiVersion: v1
kind: Service
metadata:
  name: laravel
spec:
  type: {{ .Values.service.type }}
  selector:
    app: laravel
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 80
